project_name: code_camp22
env_files:
  # This should point to the file where the github access token is stored
  github_token: /Users/andols/.ssh
before:
  hooks:
    - go mod tidy
    # This will log into to AWS.
    - aws ecr get-login-password | docker login -u AWS --password-stdin "https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$(aws configure get region).amazonaws.com"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    id: code_camp22
    main: ./cmd/code_camp22  
    binary: code_camp22

release:
  disable: true

dockers:
  # Change image template to the name of your docker repository
  - image_templates: [ "571908524012.dkr.ecr.eu-north-1.amazonaws.com/adde53/code_camp22:{{ .Tag }}"]
    dockerfile: docker/Dockerfile
    goos: linux
    goarch: amd64
    ids:
    - code_camp22
    skip_push: false