apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sinch.cc2022.codecamp22.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "sinch.cc2022.codecamp22.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{ include "sinch.cc2022.codecamp22.labels" . | indent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.registry.pullSecret }}
      containers:
        - name: codecamp22
          image: {{ template "sinch.cc2022.codecamp22.registryUrl" . }}/{{ .Values.imageCredentials.repoPath }}/{{ .Values.images.codecamp22.name }}:{{ tpl .Values.images.codecamp22.tag . }}
          imagePullPolicy: {{ .Values.imageCredentials.registry.imagePullPolicy }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
         
      